CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  location TEXT
);

CREATE TABLE promises (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  status INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  privacy INTEGER NOT NULL,
  completed_reference TEXT,
  user_id INTEGER NOT NULL, 
  FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE comments (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  text TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  promise_id INTEGER NOT NULL,
  score INTEGER NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(promise_id) REFERENCES promises(id)
);
